# Telegram token from BotFather
teloxide_token = "123teloxide_api_token"
domain_name = "mock_domain" # domain for e-mail aliasing
authorized_user_id = 1234

[kmail_api]
token = "123mock_kmail_token"
mail_id = "mock_mail_hosting_id"
mailbox_name = "mock_name"

[probe_mail]
sender_password = "mock_sender_password"
sender_email = "mock_sender_email"
sender_name = "mock_sender_name"
sender_host = "mock_sender_host"
sender_port = 1234
receiver_name = "mock_receiver_name"
